### ISSUE TITLE
Accessing the instance fails with "TypeError: filePath.replace(...).replaceAll is not a function"

### ISSUE THREAD

**Issue by terminatorbs** [TuanManhCao/digital-garden#5]
I installed this today and keep getting this error when accessing the VM on port 3000.
https://i.imgur.com/8j1PSUk.png

This is running on ubuntu 22.04, after cloning the repo and installing yarn as described in the guide.

Since google showed some results about "browser issue", I tried it with Firefox, Waterfox and Edge, the issue was the same on all of them. I'd be glad to provide more info too, but sadly i know nothing about javascript/Node etc. so just let me know what to post.

**Comment by MuRF2** [comment]
If you're seeing this error, it is likely due to the method not implemented/supported Node.js version that you're using. If you grab nodejs on Ubuntu 22.04 via the package manager apt, you install version 12.22.x. I have no idea at what time .replaceAll was implemented, however, if you use e.g. version 18.3.0 (latest release) it should work. Here is a good [installation guide](https://www.digitalocean.com/community/tutorials/how-to-install-node-js-on-ubuntu-22-04)

**Comment by terminatorbs** [comment]
sorry i haven't been back to this. seeing as i've switched to an open source alternative to obsidian a while ago and the screenshot of the error message is gone too, i'll simply close this.
